[package]
name = "ruxlibc"
version = "0.1.0"
edition = "2021"
authors = [
    "Yuekai Jia <equation618@gmail.com>",
    "yanjuguang <coolyanjg@163.com>",
    "wudashuai <wu-ds20@mails.tsinghua.edu.cn>",
    "yfblock <321353225@qq.com>",
    "scPointer <bhy18@mails.tsinghua.edu.cn>",
    "Shiping Yuan <robert_yuan@pku.edu.com>",
]
description = "Ruxos user program library for C apps"
license = "GPL-3.0-or-later OR Apache-2.0"
homepage = "https://github.com/syswonder/ruxos"
repository = "https://github.com/syswonder/ruxos/tree/main/ulib/ruxlibc"

[lib]
crate-type = ["staticlib"]

[features]
default = []

# Multicore
smp = ["ruxos_posix_api/smp"]

# Floating point/SIMD
fp_simd = ["ruxfeat/fp_simd"]

# Memory
alloc = ["ruxos_posix_api/alloc"]
paging = ["alloc", "ruxos_posix_api/paging"]
tls = ["alloc", "ruxfeat/tls"]

# Multi-task
multitask = ["ruxos_posix_api/multitask"]

# File system
fs = ["ruxos_posix_api/fs", "fd"]

# Networking
net = ["ruxos_posix_api/net", "fd"]

# Signal
signal = ["ruxos_posix_api/signal"]

# Libc features
fd = []
pipe = ["ruxos_posix_api/pipe"]
select = ["ruxos_posix_api/select"]
poll = ["ruxos_posix_api/poll"]
epoll = ["ruxos_posix_api/epoll"]
random-hw = ["ruxos_posix_api/random-hw"]

# Interrupts
irq = ["ruxos_posix_api/irq", "ruxfeat/irq"]

sched_rr = ["irq", "ruxfeat/sched_rr"]

[dependencies]
ruxfeat = { path = "../../api/ruxfeat" }
ruxos_posix_api = { path = "../../api/ruxos_posix_api" }
axio = { path = "../../crates/axio" }
axerrno = { path = "../../crates/axerrno" }

[build-dependencies]
bindgen ={ version = "0.66" }
