[package]
name = "ruxtask"
version = "0.1.0"
edition = "2021"
authors = [
    "Yuekai Jia <equation618@gmail.com>",
    "AuYang261 <xu_jyang@163.com>",
]
description = "Ruxos task management module"
license = "GPL-3.0-or-later OR Apache-2.0"
homepage = "https://github.com/syswonder/ruxos"
repository = "https://github.com/syswonder/ruxos/tree/main/modules/ruxtask"

[features]
default = []

multitask = [
    "dep:ruxconfig", "dep:percpu", "dep:spinlock", "dep:lazy_init", "dep:memory_addr",
    "dep:scheduler", "dep:timer_list", "kernel_guard", "dep:crate_interface",
]
irq = []
tls = ["ruxhal/tls"]
musl = []
preempt = ["irq", "percpu?/preempt", "kernel_guard/preempt"]

sched_fifo = ["multitask"]
sched_rr = ["multitask", "preempt"]
sched_cfs = ["multitask", "preempt"]

test = ["percpu?/sp-naive"]

[dependencies]
cfg-if = "1.0"
log = "0.4"
axerrno = { path = "../../crates/axerrno" }
ruxhal = { path = "../ruxhal" }
ruxconfig = { path = "../ruxconfig", optional = true }
ruxfdtable = { path = "../ruxfdtable" }
percpu = { path = "../../crates/percpu", optional = true }
spinlock = { path = "../../crates/spinlock", optional = true }
lazy_init = { path = "../../crates/lazy_init", optional = true }
memory_addr = { version = "0.1.0", optional = true }
scheduler = { path = "../../crates/scheduler", optional = true }
timer_list = { path = "../../crates/timer_list", optional = true }
kernel_guard = { version = "0.1.0", optional = true }
crate_interface = { version = "0.1.1", optional = true }

[dev-dependencies]
rand = "0.8"
ruxhal = { path = "../ruxhal", features = ["fp_simd"] }
ruxtask = { path = ".", features = ["test"] }
